# Generated by Django 4.0.1 on 2022-01-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the container', max_length=1000)),
                ('instructions', models.TextField(help_text='Enter any instructions required for the container', max_length=1000)),
            ],
        ),
    ]
