# Generated by Django 4.0.1 on 2022-01-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='flag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
