# Generated by Django 4.0.1 on 2022-01-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_container_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerARN', models.CharField(max_length=2048)),
                ('public_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
