# Generated by Django 4.0.1 on 2022-01-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_containerinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerinstance',
            name='container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='containers.container'),
            preserve_default=False,
        ),
    ]
