# Generated by Django 4.0.1 on 2022-01-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_remove_unit_containers'),
        ('containers', '0004_containerinstance_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit'),
        ),
    ]
