# Generated by Django 4.0.1 on 2022-01-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_container_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='unit',
        ),
    ]
