# Generated by Django 4.0.1 on 2022-01-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_unit_options'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='units',
            field=models.ManyToManyField(to='units.Unit'),
        ),
    ]
