# Generated by Django 4.0.1 on 2022-01-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_containerinstance_container'),
        ('students', '0002_remove_student_department_student_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='running_container',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.containerinstance'),
        ),
    ]
