# Generated by Django 4.0.1 on 2022-01-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(help_text='4 letter & 4 digit Unit Code <a href="https://handbooks.uwa.edu.au//search">UWA handbook</a>', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='unit',
            name='lab_facilitator',
            field=models.ManyToManyField(to='units.lab_facilitator'),
        ),
        migrations.AddField(
            model_name='unit',
            name='lecturer',
            field=models.ManyToManyField(to='units.Lecturer'),
        ),
    ]
