# Generated by Django 4.0.1 on 2022-01-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_remove_unit_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['code'], 'permissions': (('can_edit_unit', 'Edit Unit'), ('can_edit_lecturer', 'Change lecturer'), ('can_edit_facilitator', 'Change lab facilitator'))},
        ),
    ]
