# Generated by Django 4.0.1 on 2022-01-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_containerinstance_container'),
        ('units', '0009_rename_lab_facilitator_labfacilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='containers',
            field=models.ManyToManyField(to='containers.Container'),
        ),
    ]
