# Generated by Django 4.0.1 on 2022-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_remove_container_unit'),
        ('units', '0011_remove_unit_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='containers',
            field=models.ManyToManyField(to='containers.Container'),
        ),
    ]
