# Generated by Django 4.0.1 on 2022-01-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_alter_coordinator_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={},
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='last_name',
        ),
    ]
