# Generated by Django 4.0.1 on 2022-01-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0015_alter_coordinator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='coordinator',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
