# Generated by Django 4.0.1 on 2022-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0016_alter_coordinator_options_coordinator_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
