# Generated by Django 4.0.1 on 2022-01-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0017_alter_coordinator_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_unit', 'Can Edit Unit'),)},
        ),
    ]
