# Generated by Django 4.0.1 on 2022-01-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0018_alter_coordinator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
