# Generated by Django 4.0.1 on 2022-01-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_alter_coordinator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={},
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='last_name',
        ),
    ]
