# Generated by Django 4.0.1 on 2022-01-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0020_alter_coordinator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={},
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
