# Generated by Django 4.0.1 on 2022-01-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['code'], 'permissions': (('can_update_unit', 'Can Update Unit'), ('can_update_teachers', 'Can Update Teachers'))},
        ),
    ]
