# Generated by Django 4.0.1 on 2022-01-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['code'], 'permissions': (('can_update_unit', 'Can Update Unit'), ('can_update_teachers', 'Can Update Teachers'), ('can_view_all', 'Can View All Units'))},
        ),
    ]
