# Generated by Django 4.0.1 on 2022-01-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0025_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='title',
            field=models.CharField(default='', help_text='E.g. Dr. Prof. Mr.', max_length=10),
        ),
        migrations.AlterField(
            model_name='labfacilitator',
            name='title',
            field=models.CharField(default='', help_text='E.g. Dr. Prof. Mr.', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='title',
            field=models.CharField(default='', help_text='E.g. Dr. Prof. Mr.', max_length=10),
        ),
    ]
